### ISSUE TITLE
Issues with latest version 9.22 and WAS 7 with java 6 in AIX

### ISSUE THREAD

**Issue by stlpedro** [glowroot/glowroot#244] opened 2017-07-21 21:05 UTC
Hi there,

I'm getting the following errors, after I had to manually add the javax file to the current jar. any ides as to what am i missing?

2017-07-21 18:01:27.137 INFO  org.glowroot - Glowroot version: 0.9.22, built 2017-07-17 18:59:11 +0000
2017-07-21 18:01:27.142 INFO  org.glowroot - Java version: 1.6.0
2017-07-21 18:01:27.711 ERROR org.glowroot - Glowroot not started: Type org.glowroot.agent.shaded.google.errorprone.annotations.concurrent.LazyInit not present (through reference chain: org.glowroot.agent.shaded.google.common.collect.RegularImmutableList[0]->org.glowroot.agent.config.ImmutablePluginConfig["properties"])
java.lang.IllegalArgumentException: Type org.glowroot.agent.shaded.google.errorprone.annotations.concurrent.LazyInit not present (through reference chain: org.glowroot.agent.shaded.google.common.collect.RegularImmutableList[0]->org.glowroot.agent.config.ImmutablePluginConfig["properties"])
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2520)
	at org.glowroot.agent.config.ConfigFile.writeConfig(ConfigFile.java:144)
	at org.glowroot.agent.config.ConfigService.writeAll(ConfigService.java:376)
	at org.glowroot.agent.config.ConfigService.create(ConfigService.java:77)
	at org.glowroot.agent.embedded.init.EmbeddedAgentModule.<init>(EmbeddedAgentModule.java:134)
	at org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInit.init(EmbeddedGlowrootAgentInit.java:59)
	at org.glowroot.agent.MainEntryPoint.start(MainEntryPoint.java:183)
	at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:599)
	at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:599)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:335)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:350)
Caused by: org.glowroot.agent.shaded.fasterxml.jackson.databind.JsonMappingException: Type org.glowroot.agent.shaded.google.errorprone.annotations.concurrent.LazyInit not present (through reference chain: org.glowroot.agent.shaded.google.common.collect.RegularImmutableList[0]->org.glowroot.agent.config.ImmutablePluginConfig["properties"])
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:199)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:683)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2383)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2515)
	... 18 common frames omitted
Caused by: java.lang.TypeNotPresentException: Type org.glowroot.agent.shaded.google.errorprone.annotations.concurrent.LazyInit not present
	at com.ibm.oti.reflect.AnnotationHelper.getAnnotation(AnnotationHelper.java:38)
	at com.ibm.oti.reflect.AnnotationHelper.getDeclaredAnnotations(AnnotationHelper.java:50)
	at com.ibm.oti.reflect.Field.getDeclaredAnnotations(Field.java:32)
	at java.lang.reflect.Field.getDeclaredAnnotations(Field.java:1008)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass._constructField(AnnotatedClass.java:826)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass._findFields(AnnotatedClass.java:706)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass._findFields(AnnotatedClass.java:692)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass._findFields(AnnotatedClass.java:692)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveFields(AnnotatedClass.java:475)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass.fields(AnnotatedClass.java:284)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:350)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:283)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueMethod(POJOPropertiesCollector.java:169)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueMethod(BasicBeanDescription.java:222)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:348)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BasicSerializerFactory.buildMapSerializer(BasicSerializerFactory.java:764)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BasicSerializerFactory.buildContainerSerializer(BasicSerializerFactory.java:573)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:194)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:153)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1203)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1176)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.SerializerProvider.findPrimaryPropertySerializer(SerializerProvider.java:606)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddPrimarySerializer(PropertySerializerMap.java:72)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BeanPropertyWriter._findAndAddDynamic(BeanPropertyWriter.java:854)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:671)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	... 25 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.glowroot.agent.shaded.google.errorprone.annotations.concurrent.LazyInit
	at java.lang.Class.forName(Class.java:169)
	at com.ibm.oti.reflect.AnnotationHelper.getAnnotation(AnnotationHelper.java:33)
	... 50 common frames omitted
2017-07-21 18:01:33.343 INFO  org.glowroot - Glowroot version: 0.9.22, built 2017-07-17 18:59:11 +0000
2017-07-21 18:01:33.350 INFO  org.glowroot - Java version: 1.6.0
2017-07-21 18:01:33.987 ERROR org.glowroot - Glowroot not started: Type org.glowroot.agent.shaded.google.errorprone.annotations.concurrent.LazyInit not present (through reference chain: org.glowroot.agent.shaded.google.common.collect.RegularImmutableList[0]->org.glowroot.agent.config.ImmutablePluginConfig["properties"])
java.lang.IllegalArgumentException: Type org.glowroot.agent.shaded.google.errorprone.annotations.concurrent.LazyInit not present (through reference chain: org.glowroot.agent.shaded.google.common.collect.RegularImmutableList[0]->org.glowroot.agent.config.ImmutablePluginConfig["properties"])
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2520)
	at org.glowroot.agent.config.ConfigFile.writeConfig(ConfigFile.java:144)
	at org.glowroot.agent.config.ConfigService.writeAll(ConfigService.java:376)
	at org.glowroot.agent.config.ConfigService.create(ConfigService.java:77)
	at org.glowroot.agent.embedded.init.EmbeddedAgentModule.<init>(EmbeddedAgentModule.java:134)
	at org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInit.init(EmbeddedGlowrootAgentInit.java:59)
	at org.glowroot.agent.MainEntryPoint.start(MainEntryPoint.java:183)
	at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:599)
	at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:599)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:335)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:350)
Caused by: org.glowroot.agent.shaded.fasterxml.jackson.databind.JsonMappingException: Type org.glowroot.agent.shaded.google.errorprone.annotations.concurrent.LazyInit not present (through reference chain: org.glowroot.agent.shaded.google.common.collect.RegularImmutableList[0]->org.glowroot.agent.config.ImmutablePluginConfig["properties"])
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:199)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:683)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2383)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2515)
	... 18 common frames omitted
Caused by: java.lang.TypeNotPresentException: Type org.glowroot.agent.shaded.google.errorprone.annotations.concurrent.LazyInit not present
	at com.ibm.oti.reflect.AnnotationHelper.getAnnotation(AnnotationHelper.java:38)
	at com.ibm.oti.reflect.AnnotationHelper.getDeclaredAnnotations(AnnotationHelper.java:50)
	at com.ibm.oti.reflect.Field.getDeclaredAnnotations(Field.java:32)
	at java.lang.reflect.Field.getDeclaredAnnotations(Field.java:1008)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass._constructField(AnnotatedClass.java:826)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass._findFields(AnnotatedClass.java:706)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass._findFields(AnnotatedClass.java:692)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass._findFields(AnnotatedClass.java:692)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveFields(AnnotatedClass.java:475)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass.fields(AnnotatedClass.java:284)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:350)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:283)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueMethod(POJOPropertiesCollector.java:169)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueMethod(BasicBeanDescription.java:222)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:348)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BasicSerializerFactory.buildMapSerializer(BasicSerializerFactory.java:764)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BasicSerializerFactory.buildContainerSerializer(BasicSerializerFactory.java:573)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:194)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:153)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1203)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1176)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.SerializerProvider.findPrimaryPropertySerializer(SerializerProvider.java:606)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddPrimarySerializer(PropertySerializerMap.java:72)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BeanPropertyWriter._findAndAddDynamic(BeanPropertyWriter.java:854)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:671)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	... 25 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.glowroot.agent.shaded.google.errorprone.annotations.concurrent.LazyInit
	at java.lang.Class.forName(Class.java:169)
	at com.ibm.oti.reflect.AnnotationHelper.getAnnotation(AnnotationHelper.java:33)
	... 50 common frames omitted

**Comment by trask** [comment] 2017-07-21 21:23
Thanks for posting!  `ClassNotFoundException: org.glowroot.agent.shaded.google.errorprone.annotations.concurrent.LazyInit` looks like over-aggressive pruning of unused classes (proguard was introduced to trim down the jar file size recently).  I will fix this.

Can you attach the error you were getting before "manually add the javax file to the current jar"?  I'm not sure what this is.  Thanks.

**Comment by stlpedro** [comment] 2017-07-21 23:30
2017-07-21 20:29:34.981 INFO  org.glowroot - Glowroot version: 0.9.22, built 2017-07-17 18:59:11 +0000
2017-07-21 20:29:34.989 INFO  org.glowroot - Java version: 1.6.0
2017-07-21 20:29:35.202 ERROR org.glowroot - Glowroot not started: Type javax.annotation.ParametersAreNonnullByDefault not present
java.lang.TypeNotPresentException: Type javax.annotation.ParametersAreNonnullByDefault not present
	at com.ibm.oti.reflect.AnnotationHelper.getAnnotation(AnnotationHelper.java:38)
	at com.ibm.oti.reflect.AnnotationHelper.getDeclaredAnnotations(AnnotationHelper.java:50)
	at java.lang.Class.getDeclaredAnnotations(Class.java:1628)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveClassAnnotations(AnnotatedClass.java:310)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.AnnotatedClass.getAnnotation(AnnotatedClass.java:175)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.AnnotationIntrospector._findAnnotation(AnnotationIntrospector.java:1115)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector._findTypeResolver(JacksonAnnotationIntrospector.java:992)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findTypeResolver(JacksonAnnotationIntrospector.java:339)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findTypeDeserializer(BasicDeserializerFactory.java:1307)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createCollectionDeserializer(BasicDeserializerFactory.java:986)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:394)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3838)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3732)
	at org.glowroot.agent.shaded.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2698)
	at org.glowroot.agent.config.PluginCache.create(PluginCache.java:86)
	at org.glowroot.agent.embedded.init.EmbeddedAgentModule.<init>(EmbeddedAgentModule.java:115)
	at org.glowroot.agent.embedded.init.EmbeddedGlowrootAgentInit.init(EmbeddedGlowrootAgentInit.java:59)
	at org.glowroot.agent.MainEntryPoint.start(MainEntryPoint.java:183)
	at org.glowroot.agent.MainEntryPoint.premain(MainEntryPoint.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:599)
	at org.glowroot.agent.AgentPremain.premain(AgentPremain.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:599)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:335)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:350)
Caused by: java.lang.ClassNotFoundException: javax.annotation.ParametersAreNonnullByDefault
	at java.lang.Class.forName(Class.java:169)
	at com.ibm.oti.reflect.AnnotationHelper.getAnnotation(AnnotationHelper.java:33)
	... 34 common frames omitted

**Comment by stlpedro** [comment] 2017-07-24 17:18
Thank you for adding this bug to milestone 9.23 but do you know what I can do in order to fix it now? I really need to use the tool but I'm not getting anywhere just merging the jars.

Any advice would be greatly appreciated.

**Comment by trask** [comment] 2017-07-24 17:53
Hi, it's fixed in my fork https://github.com/trask/glowroot. You can clone and build that. I'm having trouble with the travis-ci build servers right now though, which is why I haven't pushed it to the main repo.

**Comment by stlpedro** [comment] 2017-07-24 17:55
Thank you Trask!

I’m not setup to do the build. Is it too much to ask for you to just give me a jar that I can use? You can just attach it here.

Thank you so much for considering my request.

-Pedro

**Comment by trask** [comment] 2017-07-24 18:24
Sure, https://glowroot.org/issues-241-and-244/glowroot-agent-0.9.23-SNAPSHOT-dist.zip

**Comment by stlpedro** [comment] 2017-07-24 18:26
Thank you!

I will try right away.

**Comment by stlpedro** [comment] 2017-07-24 18:40
Any idea about this error that im getting now?


2017-07-24 15:36:55.082 INFO  org.glowroot - Glowroot version: 0.9.23-SNAPSHOT, built 2017-07-24 18:02:44 +0000
2017-07-24 15:36:55.084 INFO  org.glowroot - Java version: 1.6.0
2017-07-24 15:36:56.551 INFO  org.glowroot - plugins loaded: Cassandra Plugin, Elasticsearch Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Logger Plugin, Play Plugin, Netty Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
2017-07-24 15:37:15.743 INFO  org.glowroot - Glowroot version: 0.9.23-SNAPSHOT, built 2017-07-24 18:02:44 +0000
2017-07-24 15:37:15.750 INFO  org.glowroot - Java version: 1.6.0
2017-07-24 15:37:17.523 INFO  org.glowroot - plugins loaded: Cassandra Plugin, Elasticsearch Plugin, Executor Plugin, Grails Plugin, Hibernate Plugin, HTTP Client Plugin, JAX-RS Plugin, Jdbc Plugin, JMS Plugin, JSF Plugin, JSP Plugin, Logger Plugin, Play Plugin, Netty Plugin, Quartz Plugin, Redis Plugin, Servlet Plugin, Spring Plugin, Struts Plugin
2017-07-24 15:38:17.432 ERROR o.g.a.util.LazyPlatformMBeanServer - platform mbean server was never created by container
2017-07-24 15:38:17.461 WARN  o.glowroot.agent.init.GaugeCollector - error accessing mbean attribute: java.lang:type=Memory HeapMemoryUsage.used
javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class com.ibm.ws.management.PlatformMBeanServerBuilder: java.lang.ClassNotFoundException: com.ibm.ws.management.PlatformMBeanServerBuilder
	at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:491)
	at javax.management.MBeanServerFactory.getNewMBeanServerBuilder(MBeanServerFactory.java:522)
	at javax.management.MBeanServerFactory.newMBeanServer(MBeanServerFactory.java:309)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:224)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:185)
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:298)
	at org.glowroot.agent.util.LazyPlatformMBeanServer.ensureInit(LazyPlatformMBeanServer.java:197)
	at org.glowroot.agent.util.LazyPlatformMBeanServer.getAttribute(LazyPlatformMBeanServer.java:137)
	at org.glowroot.agent.init.GaugeCollector.collectGaugeValues(GaugeCollector.java:191)
	at org.glowroot.agent.init.GaugeCollector.collectGaugeValues(GaugeCollector.java:164)
	at org.glowroot.agent.init.GaugeCollector.runInternal(GaugeCollector.java:121)
	at org.glowroot.agent.shaded.glowroot.common.util.ScheduledRunnable.run(ScheduledRunnable.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:452)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:328)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:161)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:109)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:192)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:216)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:896)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:735)
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.management.PlatformMBeanServerBuilder
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:136)
	at javax.management.MBeanServerFactory.loadBuilderClass(MBeanServerFactory.java:438)
	at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:476)
	... 20 common frames omitted
2017-07-24 15:38:19.113 INFO  org.glowroot - UI listening on 127.0.0.1:4000 (to access the UI from remote machines, change the bind address to 0.0.0.0, either in the Glowroot UI under Configuration > Web or directly in the admin.json file, and then restart JVM to take effect)
2017-07-24 15:38:35.430 WARN  o.glowroot.agent.init.GaugeCollector - mbean attribute FreePhysicalMemorySize not found in java.lang:type=OperatingSystem

**Comment by stlpedro** [comment] 2017-07-24 18:55
Just reporting that the UI seems to fail with the error above and it does not come up. Please let me know if there is anything else that I can provide in order to help with this bug.

**Comment by trask** [comment] 2017-07-24 19:02
What specific version of WebSphere are you using? I tested with 7.0.0.0, but maybe there is some difference in versions that I need to look at. Unfortunately I am just leaving on vacation and won't be able to look at it for a couple of days.

**Comment by stlpedro** [comment] 2017-07-24 19:06
Ho man that is not good.

This is what I got on the server.

WebSphere Platform 7.0.0.13 [ND 7.0.0.13 cf131039.07] running with process name ssfdssfCell01\ssfdssfNode01\server1 and process id 11337746
Host Operating System is AIX, version 6.1
Java version = 1.6.0, Java Compiler = j9jit24, Java VM name = IBM J9 VM


If you could help that would be great but, if not, I completely understand. I only get that one error and I’m not able to access the UI at all. I have changed the bind ip address to “0.0.0.0”

Any ideas that I can try?

**Comment by stlpedro** [comment] 2017-07-24 19:31
WebSphere Platform 7.0.0.13 [ND 7.0.0.13 cf131039.07] running with process name ssfdssfCell01\ssfdssfNode01\server1 and process id 11337746
Host Operating System is AIX, version 6.1
Java version = 1.6.0, Java Compiler = j9jit24, Java VM name = IBM J9 VM

**Comment by trask** [comment] 2017-07-27 08:23
Hi @stlpedro, please try the latest snapshot release [glowroot-agent-0.9.23-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.23-SNAPSHOT).

I wasn't able to reproduce the issue on 7.0.0.13, but this new snapshot has one additional commit on top of the earlier snapshot that tries to initialize the platform mbean server during servlet init.  If you do not have any servlets in your application deployments, this could still be an issue though.  What type of applications are deployed to your WebSphere instance?  EAR files?  WAR files?  Other?

Thanks,
Trask

**Comment by stlpedro** [comment] 2017-07-27 20:29
It works good now. Thank you! When would this be released?

The only lines in the logs are ….


                Line 1560: [7/27/17 17:24:47:992 ADT] 0000001c SystemOut     O 2017-07-27 17:24:47.988 WARN  o.glowroot.agent.init.GaugeCollector - mbean attribute FreePhysicalMemorySize not found in java.lang:type=OperatingSystem
                Line 1576: [7/27/17 17:24:49:775 ADT] 0000001e SystemOut     O 2017-07-27 17:24:49.775 INFO  org.glowroot - UI listening on 0.0.0.0:9000

**Comment by trask** [comment] 2017-07-27 22:43
That's great to hear. Next release will probably be mid next week.

**Closed by trask** 2017-07-27 22:43 UTC
Labels: bug
