### ISSUE TITLE
Roll up transaction names too high level

### ISSUE THREAD

**Issue by vguna** [glowroot/glowroot#500] opened 2018-12-30 00:58 UTC
I'm using Glowroot 0.12.3 with the central collector and using a roll up agent id to group multiple instances of the same app in a docker swarm cluster. It basically works and I can see transactions in the Glowroot UI of the central collector. It's a JAX-RS REST service using Jersey and Spring as a CDI container under the hood.

But instead of the expected REST endpoints that get called like

```
/acme/api/1/foo/bar
/acme/api/1/bar/foo
```

I only get

```
GET /acme/api/1
PUT /acme/api/1
```

grouped together as it seems.
When I look at a slow trace, it shows the expected URL (e.g. `/acme/api/1/foo/bar`) at the top though. Also If I enable the class#method option in the JAX-RS plugin, it shows different class/methods.

My service is using JAX-RS subresources a lot and puts `@Path` annotations etc. on interfaces and not on the implementation classes. Maybe this is an issue?
Any help is appreciated!

BTW: great stuff you created there!

**Comment by trask** [comment] 2019-01-03 02:17
Hi @vguna, thanks for reporting this! I think you are right that the problem is due to the annotations being on the interfaces (I didn't realize you could do that!). I will fix.

**Comment by vguna** [comment] 2019-01-03 15:36
This is great news - thanks for taking your time looking into this!

**Comment by trask** [comment] 2019-01-21 19:39
Hi @vguna, thanks again for reporting this! It should be fixed now in the latest snapshot release [glowroot-central-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.13.1-SNAPSHOT).

**Comment by trask** [comment] 2019-01-28 20:41
Hi @vguna, thanks for the example, I had no idea you could do that! Re-opening.

**Closed** 2019-02-08 06:32 UTC
Labels: bug

**Comment by trask** [comment] 2019-02-08 06:58
I'm think this should work now in the latest snapshot release [glowroot-agent-0.13.1-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.1-SNAPSHOT). Let me know how it goes. Thanks.

**Comment by vguna** [comment] 2019-02-09 09:25
I'll give it a try, thanks!

**Comment by vguna** [comment] 2019-02-23 00:54
Sorry for the late reply, but I can confirm, that 0.13.1 now shows nicely the stats per endpoints, thanks again!
I saw one special case though, where the HTTP method wasn't prefixed like for the other ones.

```
/backend/api/v1/authentication/login 1.1 %
```

Where the JAX-RS subresource looks like this:

```
	@POST
	@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	@Path("login")
	AuthenticationTokenDto login(CredentialsDto credentials);
```

So the POST prefix is missing.
The parent resource (interface) has the `@Path` set to `authentication` returning this interface.
Maybe that helps to pinpoint the problem. But never mind rest looks good!

**Comment by trask** [comment] 2019-03-18 17:17
Hi @vguna, `/backend/api/v1/authentication/login` looks like the transaction name assigned by the initial servlet capture, before it reaches the JAX-RS method (which then assigns a more specific transaction name based on the JAX-RS @Path annotations).

Maybe the `/backend/api/v1/authentication/login` transaction was from a POST that never reached the JAX-RS method (e.g. if the request did not specify `Content-Type: application/json`)?

Thanks,
Trask

**Comment by vguna** [comment] 2019-03-18 22:12
Hey.
Can't exactly tell, but I further investigate and open a new ticket if I find something.
My bet was on that "duplicate" @Path which leads to the interface above, but maybe I'm simply wrong:
```
	@Path("authentication")
	AuthenticationResource getAuthenticationResource();
```
I thought maybe it fails matching those two path elements to the URL and then simply prints out that servlet capture (losing POST). But just wild guessing here.
Thanks anyway!
