### ISSUE TITLE
Glowroot setup for jboss/Apache

### ISSUE THREAD

**Issue by chiragsindhwani** [glowroot/glowroot#494] opened 2018-12-14 18:58 UTC
I am trying to configure glowroot for the application deployed on jboss (lunux). I have placed the glowroot JAR on the linux server directory. And added following to the JVM Args for the Service inside domain.xml.

<option value="-javaagent:/opt/app/jboss/jboss-eap-6.4/modules/com/<appName>/tools/glowroot/glowroot.jar"/>

Also restarted the jboss instance on the server. However when i am trying access the following URL 

http://<hostName>:4000/ 

then page is not loaded.

However same is working on my local workspace. Note JBOSS Application Server is supported by the apache web server on top App Server.

Any configuration i am missing. Please suggest.

**Comment by trask** [comment] 2018-12-14 19:04
Hi @chiragsindhwani, thanks for posting! The default bind port is `127.0.0.1` which is not accessible from other machines. Check the glowroot agent log file, it should log a message about this and how to resolve.

**Comment by trask** [comment] 2018-12-14 23:42
Can you see if there are any other JVM processes running with the glowroot agent? E.g. `ps -ef | grep glowroot`

**Comment by trask** [comment] 2019-01-14 00:13
Closing, but please re-open if you are still facing this issue. Thanks.

**Closed by trask** 2019-01-14 00:13 UTC

**Comment by mrireddy04** [comment] 2024-07-25 20:24
Hi @trask 
 I have upgraded  wildfly to wildfly 26 and and download glowroot 0.14.0 distribution.  
I am getting this error in the log file.
Glowroot UI comes up though.
Is there any configuration I am missing.



024-07-24 16:14:54.190 INFO  org.glowroot - Glowroot version: 0.14.2, built 2024-04-06 19:02:00 +0000
2024-07-24 16:14:54.192 INFO  org.glowroot - Java version: 11.0.9 (AdoptOpenJDK / Windows 10)
2024-07-24 16:14:54.192 INFO  org.glowroot - Java args: -Xms12G -Xmx12G -XX:-TieredCompilation -XX:+UseG1GC -XX:ConcGCThreads=12 -XX:ParallelGCThreads=22 -XX:MaxGCPauseMillis=500 -XX:InitiatingHeapOccupancyPercent=40 -XX:G1HeapWastePercent=2 -XX:G1ReservePercent=15 -XX:+UnlockExperimentalVMOptions -XX:G1OldCSetRegionThresholdPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1NewSizePercent=15 -XX:G1MaxNewSizePercent=25 -XX:+UseLargePages -Xlog:gc*:file="C:\Home\wildfly-26.1.2.Final\standalone\log\gc.log":time,uptime:filecount=10,filesize=10M -javaagent:C:/Home/glowroot/glowroot.jar --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-exports=java.naming/com.sun.jndi.url.ldap=ALL-UNNAMED --add-exports=java.naming/com.sun.jndi.url.ldaps=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED
2024-07-24 16:14:55.959 INFO  org.glowroot - creating glowroot schema...
2024-07-24 16:14:56.070 INFO  org.glowroot - glowroot schema created
2024-07-24 16:14:56.849 INFO  org.glowroot - UI listening on 127.0.0.1:4000 (to access the UI from remote machines, change the bind address to 0.0.0.0, either in the Glowroot UI under Configuration > Web or directly in the admin.json file, and then restart JVM to take effect)
2024-07-24 16:15:15.267 ERROR o.g.a.p.servlet.ContainerStartup_ - could not create platform mbean server: java/lang/management/ManagementFactory
java.lang.NoClassDefFoundError: java/lang/management/ManagementFactory
	at javax.servlet.api@2.0.0.Final//org.glowroot.agent.plugin.servlet.ContainerStartup_.initPlatformMBeanServer(ContainerStartup.java:58)
	at javax.servlet.api@2.0.0.Final//org.glowroot.agent.plugin.servlet.ServletAspect$ServiceInitAdvice_.onBefore(ServletAspect.java:439)
	at javax.servlet.api@2.0.0.Final//javax.servlet.GenericServlet.init(GenericServlet.java)
	at deployment.hawtio-war-3.0.1.war//io.hawt.web.proxy.ProxyServlet.init(ProxyServlet.java:119)
	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.RunAsLifecycleInterceptor.doIt(RunAsLifecycleInterceptor.java:70)
	at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:76)
	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:309)
	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:145)
	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588)
	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@26.1.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at org.wildfly.extension.undertow@26.1.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at org.wildfly.extension.undertow@26.1.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at org.wildfly.extension.undertow@26.1.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at io.undertow.servlet@2.2.19.Final//io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
	at org.wildfly.extension.undertow@26.1.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:106)
	at org.wildfly.extension.undertow@26.1.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:87)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.ClassNotFoundException: java.lang.management.ManagementFactory from [Module "javax.servlet.api" version 2.0.0.Final from local module loader @12704e15 (finder: local module finder @512575e9 (roots: C:\Home\wildfly-26.1.2.Final\modules,C:\Home\wildfly-26.1.2.Final\modules\system\layers\fuse,C:\Home\wildfly-26.1.2.Final\modules\system\layers\base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:200)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 29 common frames omitted
