### ISSUE TITLE
NoSuchMethodError error in case of ThreadPoolExecutor's Callable task

### ISSUE THREAD

**Issue by gamefundas** [glowroot/glowroot#274] opened 2017-09-29 04:00 UTC
After enabling glowroot in my application, soon I started seeing failures with Callable tasks
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: java.lang.Object.call()Ljava/lang/Object;
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)

I am using Java 8 and Spring Boot 1.5

**Comment by trask** [comment] 2017-09-29 16:54
Hi @gamefundas, thanks for reporting this, can you post the stack trace for the "caused by" (NoSuchMethodError) exception? Thanks.

**Comment by trask** [comment] 2017-11-01 04:57
Closing, but feel free to re-open if there is any update, thanks.

**Closed by trask** 2017-11-01 04:57 UTC
