### ISSUE TITLE
Not able to see gauges under JVM Gauges

### ISSUE THREAD

**Issue by risrikanth** [glowroot/glowroot#319] opened 2018-02-02 02:15 UTC
Hi Trask,

I am testing one functionality in  glowroot-central-0.10.1 collector. When I select JVM and gauges, initially it is showing time dropdown  default value as "Invalid date, Invalid Date to Invalidate date" . When I select dropdown with 30min, 4hr... selected agent dropdown is clearing out and not able to see anything. I am attaching screen shot here for reference.
[Agents-GaugesIssue-glowroot-central-0.10.1-dist.docx](https://github.com/glowroot/glowroot/files/1687871/Agents-GaugesIssue-glowroot-central-0.10.1-dist.docx)

**Comment by trask** [comment] 2018-02-02 02:21
Hi @risrikanth, what browser/version are you using?  I will see if I can repro.  Thanks.

**Comment by risrikanth** [comment] 2018-02-02 03:53
Thanks for quick response..
I am using FireFox ESR  52.5.0(32 bit)

**Comment by trask** [comment] 2018-02-02 05:45
Hi @risrikanth, I was not able to reproduce what you are seeing, but there were a couple of Javascript errors on that page, so I fixed those errors in the latest snapshot release and hopefully that will resolve the issue you are seeing. Can you try out the latest snapshot release [glowroot-central-0.10.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.2-SNAPSHOT) and let me know? Thanks.

**Comment by trask** [comment] 2018-02-19 05:04
Closing, but feel free to re-open if you are still seeing any issue.  Thanks.

**Closed by trask** 2018-02-19 05:04 UTC
Labels: bug
