### ISSUE TITLE
openj9 / ibm j9 broken after 0.11.0

### ISSUE THREAD

**Issue by bmhm** [glowroot/glowroot#522] opened 2019-02-04 09:29 UTC
Hi,

after Upgrading from 0.11.0 to 0.13.0, I cannot see heap dumps, the mbean tree of other things in the JVM tab.

Before the upgrade, I could see entries in the mbean tree, the threaddump, forcegc button, system properties and environment.
Now, every entry shows this error:

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.glowroot.ui.CommonHandler.callMethod(CommonHandler.java:586)
	at org.glowroot.ui.CommonHandler.handleJsonServiceMappings(CommonHandler.java:325)
	at org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:236)
	at org.glowroot.ui.CommonHandler.handle(CommonHandler.java:160)
	at org.glowroot.central.GlowrootServlet.service(GlowrootServlet.java:93)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1208)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1005)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:927)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1011)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:414)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:373)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:532)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:466)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:331)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:811)
Caused by: java.lang.AbstractMethodError: org/glowroot/agent/plugin/executor/ExecutorAspect$RunnableEtcMixin.glowroot$setAuxContext(Lorg/glowroot/agent/plugin/api/AuxThreadContext;)V
	at org.glowroot.agent.plugin.executor.ExecutorAspect$ScheduleAdvice.onBefore(ExecutorAspect.java:208)
	at org.infinispan.executors.LazyInitializingScheduledExecutorService.schedule(LazyInitializingScheduledExecutorService.java)
	at org.infinispan.manager.impl.LocalClusterExecutor.submitConsumer(LocalClusterExecutor.java:84)
	at org.infinispan.manager.impl.AllClusterExecutor.startLocalInvocation(AllClusterExecutor.java:66)
	at org.infinispan.manager.impl.AllClusterExecutor.submitConsumer(AllClusterExecutor.java:165)
	at org.infinispan.manager.ClusterExecutor.submitConsumer(ClusterExecutor.java:116)
	at org.glowroot.central.util.ClusterManager$DistributedExecutionMapImpl.execute(ClusterManager.java:474)
	at org.glowroot.central.DownstreamServiceImpl.runOnCluster(DownstreamServiceImpl.java:439)
	at org.glowroot.central.DownstreamServiceImpl.mbeanDump(DownstreamServiceImpl.java:242)
	at org.glowroot.central.LiveJvmServiceImpl.getMBeanDump(LiveJvmServiceImpl.java:81)
	at org.glowroot.ui.JvmJsonService.getMBeanTree(JvmJsonService.java:395)
	... 31 more

```

// Update:
Also will not work when connecting to an agent running Oracle JDK.

**Comment by trask** [comment] 2019-02-06 01:55
Hi @bmhm, thanks for reporting this!

What JVM / version are you running the central collector with?

It looks like you are monitoring the central collector with the glowroot agent, what version of the glowroot agent are you using to monitor your central collector?

Can you post the glowroot agent log for the agent that is monitoring the central collector itself?

Thanks,
Trask

**Comment by bmhm** [comment] 2019-02-06 12:04
I am using the same agent and Central version. But the agent cannot detect the central version.
See also my Google groups discussion, which has a similar issue.

**Comment by trask** [comment] 2019-02-07 05:53
The unknown version issue should be fixed now in the latest snapshot release [glowroot-central-0.13.1-SNAPSHOT-dist.war](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=war&v=0.13.1-SNAPSHOT).

I couldn't reproduce the `java.lang.AbstractMethodError`.

Can you post your `jvm.options` file (from `wlp/usr/servers/...`)?

**Comment by bmhm** [comment] 2019-02-08 07:24
Sure, here you go: https://pastebin.com/fkL8ZxEj

**Comment by trask** [comment] 2019-02-08 18:48
Hi @bmhm, I'm confused because I can see that the glowroot agent is monitoring the central collector itself because of the stack trace:

```
	...
	at org.glowroot.agent.plugin.executor.ExecutorAspect$ScheduleAdvice.onBefore(ExecutorAspect.java:208)
	at org.infinispan.executors.LazyInitializingScheduledExecutorService.schedule(LazyInitializingScheduledExecutorService.java)
	at org.infinispan.manager.impl.LocalClusterExecutor.submitConsumer(LocalClusterExecutor.java:84)
	at org.infinispan.manager.impl.AllClusterExecutor.startLocalInvocation(AllClusterExecutor.java:66)
	at org.infinispan.manager.impl.AllClusterExecutor.submitConsumer(AllClusterExecutor.java:165)
	at org.infinispan.manager.ClusterExecutor.submitConsumer(ClusterExecutor.java:116)
	at org.glowroot.central.util.ClusterManager$DistributedExecutionMapImpl.execute(ClusterManager.java:474)
	...
```

but I don't see `-javaagent:path/to/glowroot.jar` in your `jvm.options` file.

Maybe you added `-javaagent:path/to/glowroot.jar` somewhere else? Thanks.

**Comment by bmhm** [comment] 2019-02-11 11:03
Hi @trask,

I just omnitted those two lines (javaAgent and agent_name).
Anyway, even when viewing other JVMs, I get the very same error message.

I just added glowroot everywhere where I deploy my application server. In 0.11.0, I never had any problems with this.

**Comment by trask** [comment] 2019-02-11 18:00
Hi @bmhm, can you post the agent log from the agent_name log dir (the one that is monitoring the central collector itself)?

**Comment by bmhm** [comment] 2019-02-13 15:51
Hi @trask ,

when I start up a collector freshly and target that specific page (e.g. thread dump of another agent), this is the whole output from liberty's `console.log`:

```
2019-02-13 16:43:59.722 INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
2019-02-13 16:43:59.913 INFO  org.glowroot - connected to Cassandra (version 3.11.3), using keyspace 'glowroot' (replication factor 1) and consistency level QUORUM
2019-02-13 16:44:05.733 INFO  org.glowroot - gRPC listening on 127.0.0.1:8183
2019-02-13 16:44:07.175 INFO  org.glowroot - startup complete
2019-02-13 16:44:07.179 INFO  com.ibm.ws.webcontainer.servlet - SRVE0242I: [glowroot] [/] [org.glowroot.central.GlowrootServlet]: Initialization successful.
[AUDIT   ] CWWKZ0001I: Application glowroot started in 25.618 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [jsp-2.2, servlet-3.1, websocket-1.1].
[AUDIT   ] CWWKF0011I: The server glowroot-central.3 is ready to run a smarter planet.
2019-02-13 16:44:11.680 INFO  com.datastax.driver.core.utils.UUIDs - PID obtained through native call to getpid(): 113629
2019-02-13 16:44:27.924 WARN  o.glowroot.agent.init.GaugeCollector - mbean not matched: WebSphere:type=ConnectionPoolStats,name=* (waited 60 seconds after jvm startup before logging this warning to allow time for mbean registration - this wait time can be changed under Configuration > Advanced)
2019-02-13 16:45:15.054 ERROR org.glowroot.ui.CommonHandler - null
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.glowroot.ui.CommonHandler.callMethod(CommonHandler.java:586)
        at org.glowroot.ui.CommonHandler.handleJsonServiceMappings(CommonHandler.java:325)
        at org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:236)
        at org.glowroot.ui.CommonHandler.handle(CommonHandler.java:160)
        at org.glowroot.central.GlowrootServlet.service(GlowrootServlet.java:95)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1221)
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4954)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:996)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1023)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:376)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:532)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:466)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:331)
        at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:232)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:812)
Caused by: java.lang.AbstractMethodError: org/glowroot/agent/plugin/executor/ExecutorAspect$RunnableEtcMixin.glowroot$setAuxContext(Lorg/glowroot/agent/plugin/api/AuxThreadContext;)V
        at org.glowroot.agent.plugin.executor.ExecutorAspect$ScheduleAdvice.onBefore(ExecutorAspect.java:208)
        at org.infinispan.executors.LazyInitializingScheduledExecutorService.schedule(LazyInitializingScheduledExecutorService.java)
        at org.infinispan.manager.impl.LocalClusterExecutor.submitConsumer(LocalClusterExecutor.java:84)
        at org.infinispan.manager.impl.AllClusterExecutor.startLocalInvocation(AllClusterExecutor.java:66)
        at org.infinispan.manager.impl.AllClusterExecutor.submitConsumer(AllClusterExecutor.java:165)
        at org.infinispan.manager.ClusterExecutor.submitConsumer(ClusterExecutor.java:116)
        at org.glowroot.central.util.ClusterManager$DistributedExecutionMapImpl.execute(ClusterManager.java:474)
        at org.glowroot.central.DownstreamServiceImpl.runOnCluster(DownstreamServiceImpl.java:441)
        at org.glowroot.central.DownstreamServiceImpl.threadDump(DownstreamServiceImpl.java:169)
        at org.glowroot.central.LiveJvmServiceImpl.getThreadDump(LiveJvmServiceImpl.java:45)
        at org.glowroot.ui.JvmJsonService.getThreadDump(JvmJsonService.java:174)
        ... 32 common frames omitted
```

An this is the content of `glowroot-central.log`:
```
2019-02-13 16:43:50.606 WARN  org.glowroot.common.util.Version - could not find Build-Time attribute in META-INF/MANIFEST.MF file
2019-02-13 16:43:50.631 INFO  org.glowroot - Glowroot version: 0.13.1-SNAPSHOT, commit 93e736cbba
2019-02-13 16:43:50.635 INFO  org.glowroot - Java version: 1.8.0_191
2019-02-13 16:43:50.636 INFO  org.glowroot - Glowroot home: /opt/wlp/usr/servers/glowroot-central.3/properties
2019-02-13 16:43:52.605 INFO  o.i.f.GlobalComponentRegistry - ISPN000128: Infinispan version: Infinispan 'Infinity Minus ONE +2' 9.4.5.Final
2019-02-13 16:43:53.684 INFO  o.i.r.t.jgroups.JGroupsTransport - ISPN000078: Starting JGroups channel ISPN
2019-02-13 16:43:54.151 INFO  org.infinispan.CLUSTER - ISPN000094: Received new cluster view for channel ISPN: [sername-6944|38] (3) [servername-6944, servername-36718, servername-63701]
2019-02-13 16:43:54.298 INFO  o.i.r.t.jgroups.JGroupsTransport - ISPN000079: Channel ISPN local address is servername-63701, physical addresses are [127.0.0.1:7802]
2019-02-13 16:43:57.753 INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
2019-02-13 16:43:57.783 INFO  com.datastax.driver.core - DataStax Java driver 3.6.0 for Apache Cassandra
2019-02-13 16:43:57.791 INFO  c.d.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
2019-02-13 16:43:58.161 INFO  com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
2019-02-13 16:43:59.718 INFO  c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
2019-02-13 16:43:59.721 INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
2019-02-13 16:43:59.722 INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.2:9042 added
2019-02-13 16:43:59.913 INFO  org.glowroot - connected to Cassandra (version 3.11.3), using keyspace 'glowroot' (replication factor 1) and consistency level QUORUM
2019-02-13 16:44:05.733 INFO  org.glowroot - gRPC listening on 127.0.0.1:8183
2019-02-13 16:44:07.175 INFO  org.glowroot - startup complete
2019-02-13 16:44:07.179 INFO  com.ibm.ws.webcontainer.servlet - SRVE0242I: [glowroot] [/] [org.glowroot.central.GlowrootServlet]: Initialization successful.
2019-02-13 16:44:11.680 INFO  com.datastax.driver.core.utils.UUIDs - PID obtained through native call to getpid(): 113629
2019-02-13 16:45:15.054 ERROR org.glowroot.ui.CommonHandler - null
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.glowroot.ui.CommonHandler.callMethod(CommonHandler.java:586)
        at org.glowroot.ui.CommonHandler.handleJsonServiceMappings(CommonHandler.java:325)
        at org.glowroot.ui.CommonHandler.handleRequest(CommonHandler.java:236)
        at org.glowroot.ui.CommonHandler.handle(CommonHandler.java:160)
        at org.glowroot.central.GlowrootServlet.service(GlowrootServlet.java:95)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1221)
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4954)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:996)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1023)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:376)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:532)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:466)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:331)
        at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:232)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:812)
Caused by: java.lang.AbstractMethodError: org/glowroot/agent/plugin/executor/ExecutorAspect$RunnableEtcMixin.glowroot$setAuxContext(Lorg/glowroot/agent/plugin/api/AuxThreadContext;)V
        at org.glowroot.agent.plugin.executor.ExecutorAspect$ScheduleAdvice.onBefore(ExecutorAspect.java:208)
        at org.infinispan.executors.LazyInitializingScheduledExecutorService.schedule(LazyInitializingScheduledExecutorService.java)
        at org.infinispan.manager.impl.LocalClusterExecutor.submitConsumer(LocalClusterExecutor.java:84)
        at org.infinispan.manager.impl.AllClusterExecutor.startLocalInvocation(AllClusterExecutor.java:66)
        at org.infinispan.manager.impl.AllClusterExecutor.submitConsumer(AllClusterExecutor.java:165)
        at org.infinispan.manager.ClusterExecutor.submitConsumer(ClusterExecutor.java:116)
        at org.glowroot.central.util.ClusterManager$DistributedExecutionMapImpl.execute(ClusterManager.java:474)
        at org.glowroot.central.DownstreamServiceImpl.runOnCluster(DownstreamServiceImpl.java:441)
        at org.glowroot.central.DownstreamServiceImpl.threadDump(DownstreamServiceImpl.java:169)
        at org.glowroot.central.LiveJvmServiceImpl.getThreadDump(LiveJvmServiceImpl.java:45)
        at org.glowroot.ui.JvmJsonService.getThreadDump(JvmJsonService.java:174)
        ... 32 common frames omitted
```

**Comment by trask** [comment] 2019-02-13 18:00
Hi @bmhm, these are both central collector logs, I'm interested to the see agent log from the agent that is monitoring the central collector itself.

If it's not clear what I'm looking for, can you post your full `jvm.options` file (including the `-javaagent` and `agent_name` args), then I can direct you to the exact directory/file I'm looking for.

Thanks,
Trask

**Comment by bmhm** [comment] 2019-02-14 08:29
Hi @trask ,

there are no log entries when I click on that menu item.
There are some "excessive backlog" entries, but that's it.

(btw: how would I know if I need another cassandra instance or another glowroot central instance?)

**Comment by trask** [comment] 2019-02-14 19:21
Hi @bmhm, can you post your full `jvm.options` file (for the WebSphere that is running the central collector), including the `-javaagent:path/to/glowroot.jar` and `-Dglowroot.agent.id` args?

**Closed** 2019-03-19 02:39 UTC

**Comment by trask** [comment] 2019-03-19 04:47
Hi @bmhm, I think this should be fixed now in the latest snapshot release [glowroot-agent-0.13.2-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.13.2-SNAPSHOT).
