### ISSUE TITLE
warning in the logs: extend() transaction currentTimer is null

### ISSUE THREAD

**Issue by aoganesi** [glowroot/glowroot#418] opened 2018-07-11 23:46 UTC
Hi,

We are noticing our logs flooded with the following Warning
`WARN  org.glowroot.agent.impl.TimerImpl - extend() transaction currentTimer is null`
In debug I see that it is generated in TimerImpl.extend(long startTick) method invoked from JDBC plugin (onBeforeCommon) callback. Below is a quick recap of the instrumented code that generates it.

```
// Instrumented method which identifies the timerName "Report Release"
private ScrollableCursor getPendingReports()
{
//   executes query and returns a scrollable cursor
    return sc;
}

// Non-instrumented method
private void process_reports()
{
    ScrollableCursor sc = getPendingReports();
    while (sc.hasMoreElements())  // **this call ends up in the JDBC plugin and generates the warning ** 
    {
       // do stuff
    }
}
```
Could you please advise:
- Is there a way to configure the system to avoid the warning? (i.e. what are we doing wrong?)
- Could we suppress it in the **server log** and in the **glowroot central** log? 

Thank you!

**Comment by trask** [comment] 2018-07-12 02:37
Hi @aoganesi, thanks for reporting this!

I think the problem is that the instrumented transaction is captured on `getPendingReports()`, and so this transaction is completed before the ScrollableCursor is iterated.

Can you try putting the instrumentation on `process_reports()` instead, so it covers both the query and iteration?

Thanks,
Trask

**Comment by aoganesi** [comment] 2018-07-12 04:44
Hi Trask,

Thank you for looking into this!

Indeed, the issue stems from the fact that by the time ScrollableCursor is iterated, instrumented method is done. The reason why we chose not to instrument `process_reports()` is great variability in execution time depending on the number of reports to release, so we chose to instrument `getPendingReports()` (to measure query performance) and subsequent methods that work on one report at a time  and exclude the Scrollable cursor iteration method (to have consistent benchmarking). I hope that's not a bad practice, is it?

I found a parameter in Jdbc Plugin settings "Capture timings for ResultSet navigation" and decided to turn it off for our circumstances. It seems to address exactly this issue and the warning stopped after that. Are there any drawbacks to this? 

Is it possible to deploy this configuration with our agents, so that I don't have to disable it for each agent in the Central configuration?

Thank you!
Tony.

**Comment by trask** [comment] 2018-07-12 04:53
Hi Tony,

Yeah, don't close this issue, I will probably fix this, you aren't doing anything wrong.

I'm glad you found a workaround.

You can deploy new agents with pre-populated `config.json` file.  This only works for new agents that don't already have a configuration stored in the central collector.  See more discussion at #213.

Thanks,
Trask

**Closed** 2018-07-19 23:18 UTC

**Comment by trask** [comment] 2018-07-20 04:23
Hi @aoganesi, this is fixed now in the latest snapshot release [glowroot-agent-0.10.13-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.10.13-SNAPSHOT).

**Comment by trask** [comment] 2018-07-21 00:15
👍
