### ISSUE TITLE
Alerts - distinguish which glowroot instance the alert comes from.

### ISSUE THREAD

**Issue by john-keysight** [glowroot/glowroot#233] opened 2017-07-05 19:06 UTC
I'd like to be able to distinguish which instance of Glowroot an Alert message is coming from. We are running multiple instances of Glowroot, one each on DEV, QA, and Production servers. Currently I don't see a way of distinguishing which server the Glowroot alert message is coming from as the "From" address is always the same, our SMTP address.  I was hoping the "From display name" in the SMTP configuration would be included in the message or subject and I could use something like "Glowroot - QA Server", "GLowroot - Production Server" to tell which server is alerting, but this field doesn't appear to show up anywhere in the email. Would it be possible to include the SMTP "From display name" in the Alert message?

**Comment by xz64** [comment] 2017-09-15 13:04
@john-keysight  @trask 

What do you think of adding the glowroot.agent.id (if configured) to the beginning of each subject (and maybe somewhere in the message too)? I think that would help a lot especially if people are configuring their glowroot agent id's to include identifiers for QA/Production. I would like to take a stab at implementing this if you are ok with it.

**Comment by john-keysight** [comment] 2017-09-18 22:51
Where is glowroot.agent.id configured?  What you describe of entering it in the subject and/or somewhere in the text would be great.

I was expecting “From Display name” from SMTP configuration to be included somewhere, but another field such as glowroot.agent.id would be just as adequate as long as it is specific to the server. I’m just not aware of where glowroot.agent.id is configured.


[cid:image001.png@01D33095.768B0900]

**Comment by xz64** [comment] 2017-09-19 01:04
glowroot.agent.id is a system property specified on the command line to differentiate JVMs running on the same host. It is documented here: https://github.com/glowroot/glowroot/wiki/Agent-Installation

**Comment by trask** [comment] 2017-09-19 16:45
Hi @xz64, sorry for the delay in responding, this sounds like a great idea.  When running multiple agents on one box we can use the already configured `-Dglowroot.agent.id=...`, and when not running multiple agents on one box, `agent.id` can be configured in `glowroot.properties`.  Feel free to send partial PR or point me to your fork if you have any questions/issues and I can review.  Thanks.

**Comment by trask** [comment] 2017-09-19 17:19
Hi @john-keysight, @xz64, `-Dglowroot.agent.id=...` should only be used when running multiple agents on one box, since it triggers the creation of a subdirectory (under the glowroot directory) for each agent to store its own configuration and data.  When not running multiple agents on one box, we can use `agent.id` in the `glowroot.properties` file for this.

I'm also thinking (after the above change) of adding a "General" sidebar item in the Administration section with something like "Agent display name", in order to make this more discoverable (the above change still makes sense, to default to the `agent.id`, especially in the case of multiple agents on one box where this is already configured).  Also, when "Agent display name" is configured, I'm thinking to display that value prominently in the UI (similar to how the agent name is displayed in the central collector).

**Comment by john-keysight** [comment] 2017-09-19 21:39
This sounds good to me.

Thanks,
John

**Comment by xz64** [comment] 2017-09-21 03:58
@trask  I have started some work on the fork here:

https://github.com/glowroot/glowroot/compare/master...xz64:agent_id_in_email

What would be the best way to get the agent.id from glowroot.properties in the AlertingService class?

**Comment by john-keysight** [comment] 2017-09-21 14:57
I’m not quite sure what you are asking.

If you are asking where in the Glowroot UI to put and entry for agent.id, I’d expect it in “Configuration” menu. And the closest submenu would be “Advanced”.
If you are asking a programming question, that’s beyond my knowledge.


-best regards,
John

**Comment by trask** [comment] 2017-09-21 19:28
Hi @xz64, my thought is to pass that into the method using `agentRollupId` parameter (which is currently only used by the central collector)

**Comment by xz64** [comment] 2017-09-22 04:10
Ok, can you help me find out where agentRollupId is being passed from? I think it is from CollectorImpl.java but it appears to be hardcoded to an empty string. I'm trying to get an idea of the classes that should be changed.

**Comment by john-keysight** [comment] 2017-09-22 14:36
Sorry, but I’m not a programmer, just a user of Glowroot. I wouldn’t know where to start.

**Comment by xz64** [comment] 2017-09-22 15:09
@john-keysight  No worries, my message was intended for @trask  . If you do not wish to receive emails regarding this issue, you can click the "mute the thread link" at the end of the email.

**Comment by john-keysight** [comment] 2017-09-22 15:11
Ah, thanks for the explanation. I’ve been confused about these.

**Comment by trask** [comment] 2017-12-05 03:11
Sorry for the delay.  You can now configure an optional display name for the agent under Administration > General (e.g. https://demo.glowroot.org/admin/general), and this will be used when sending out the alert email.

This is available in the latest snapshot release [glowroot-agent-0.9.29-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.29-SNAPSHOT).

**Comment by john-keysight** [comment] 2017-12-06 23:11
Hi Trask,

Thanks for the change. Should there be a save changes button, below The Agent display name entry?  I’m not seeing a way to save the changes and get the message that I have unsaved changes if I try to navigate away.

Nice description of what the feature is supposed to do.

-best regards,
John


[cid:image001.png@01D36EA4.832C5950]
[cid:image002.png@01D36EA4.832C5950]

**Comment by trask** [comment] 2017-12-07 00:07
Oops! This is fixed in the latest snapshot release [glowroot-agent-0.9.29-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-agent&c=dist&e=zip&v=0.9.29-SNAPSHOT). Thanks for reporting it.

**Comment by john-keysight** [comment] 2017-12-07 20:38
Thanks Trask,

That works better. Verified it works on the UI and alert emails.  Doesn’t work with the “SMTP Configuration, Send test email” function, but that’s not a real issue for me.

-thanks again and best regards,
John wilson

**Comment by john-keysight** [comment] 2017-12-08 20:04
Seeing alerts come in today with the server labeled. This is great!  Thanks.
-john

**Comment by anveshgkumar** [comment] 2017-12-11 20:14
@trask 
I have downloaded the latest snapshot release glowroot-agent-0.9.29-SNAPSHOT-dist.zip file to setup some alerts. There was no **General** option under Settings >Administration. What we are looking for is How can we configure the email body/subject with the following details:
`Agent rollup id`, and 
`Environment of a collector which is sending the alert` 
For example: PROD/TEST, will they be configurable as a parameters on the central collector.

![image](https://user-images.githubusercontent.com/20775222/33851754-94ae9d98-de7d-11e7-8d4a-4ddfb7120f04.png)

**Comment by trask** [comment] 2017-12-12 03:32
@john-keysight Thanks for the note about the test emails, this is included now in the latest snapshot.

**Comment by trask** [comment] 2017-12-12 03:35
Hi @anveshgkumar, thanks for posting!  This was only implemented for standalone agents (not reporting to a central collector).  Re-opening to think about adding support when running multiple central collectors.

**Comment by john-keysight** [comment] 2017-12-12 15:49
Hi Trask,

So nice to be able to see the server in the subject line of the email:

[cid:image001.png@01D3731D.C592BB90]

Cuts the troubleshooting down significantly.

THANKS again,
john

**Comment by pavanie** [comment] 2017-12-13 17:46
Hi Trask - Thanks for reopening this item. Is there a time frame when we can we expect a fix for central collector alerts?

**Comment by trask** [comment] 2017-12-15 05:53
Hi @pavanie, probably next week.

**Comment by trask** [comment] 2018-01-02 04:46
Hi @pavanie, just wanted to give you an update, working on finishing up this issue along with #155, #249 and #296 this week.

**Comment by pavanie** [comment] 2018-01-02 14:43
Thanks Trask!

**Closed** 2018-01-12 04:37 UTC
Labels: enhancement

**Comment by trask** [comment] 2018-01-12 05:23
This is available now in the latest central snapshot [glowroot-central-0.10.0-SNAPSHOT-dist.zip](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=zip&v=0.10.0-SNAPSHOT) (or [glowroot-central-0.10.0-SNAPSHOT-dist.war](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.glowroot&a=glowroot-central&c=dist&e=war&v=0.10.0-SNAPSHOT)).
