### ISSUE TITLE
Glowroot central is not starting: standard_init_linux.go:211: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by mnatsakanyank** [glowroot/glowroot#735] opened 2020-07-08 08:41 UTC
Glowroot central docker is not starting

`docker run --name myglowroot2 \                                                                                                                                       kmnatsakanya@ZALANDO-11440
           --link mycassandra:cassandra \
           --publish 0.0.0.0:4000:4000 \
           --publish 0.0.0.0:8181:8181 \
           glowroot/glowroot-central:0.13.6`

`standard_init_linux.go:211: exec user process caused "no such file or directory"`

**Comment by felipelutz** [comment] 2020-07-09 15:21
This looks like a duplicate of #626. There's a workaround there that you can follow.
By the way, I had the same problem, and I resolved following the instructions there.

**Comment by shivpathak** [comment] 2020-08-04 14:33
I am also getting the same issue due to special character `^M` in `docker-entrypoint.sh` and `glowroot-central.sh`

fix is quit simple but the problem is we have to maintain our own custom image instead of using directly the official one due the the following change:

1 - Open terminal pull and run docker image with entrypoint `/bin/bash`

```
user@mylaptop$ docker pull glowroot/glowroot-central:0.13.6
user@mylaptop$ docker run -it --entrypoint /bin/bash 8da922f4b984
glowroot@7ee9c37d5a49:/usr/share/glowroot-central$ dos2unix glowroot-central.sh
glowroot@7ee9c37d5a49:/usr/share/glowroot-central$ dos2unix docker-entrypoint.sh
```
2 - After above command executed open another terminal and run following command
```
docker login my.docker.registry.com
docker commit 7ee9c37d5a49 my.docker.registry.com/infra/glowroot/v0.13.6:special-char-fix
docker push my.docker.registry.com/infra/glowroot/v0.13.6:special-char-fix
```
**Note-** Please note here my.docker.registry.com and container ID will differ.

**Comment by mturra-Pro** [comment] 2021-05-18 10:28
This works with names instead of ids:
1 - Open terminal pull and run docker image with entrypoint `/bin/bash`

```
docker pull glowroot/glowroot-central:0.13.6
docker run -it --entrypoint --name glowroot-central  /bin/bash glowroot/glowroot-central:0.13.6
```
2 - After above command executed **open another terminal** and run following command

```
docker cp glowroot-central:/usr/local/bin/docker-entrypoint.sh /tmp/docker-entrypoint.sh
docker cp glowroot-central:/usr/local/bin/glowroot-central.sh /tmp/glowroot-central.sh

dos2unix /tmp/glowroot-central.sh /tmp/docker-entrypoint.sh

docker cp /tmp/glowroot-central.sh glowroot-central::/usr/local/bin/glowroot-central.sh
docker cp /tmp/docker-entrypoint.sh glowroot-central::/usr/local/bin/docker-entrypoint.sh

docker commit glowroot-central: glowroot/glowroot:v0.13.6-special-char-fix
```
 
 3 - After all above steps I could use my own image glowroot/glowroot:v0.13.6-special-char-fix in kubernetes deployment or as docker run.

**Comment by mturra-Pro** [comment] 2021-05-18 10:33
Patch for Dockerfile

```
Index: central/Dockerfile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/central/Dockerfile b/central/Dockerfile
--- a/central/Dockerfile	(revision ace6a8c5b78796a22b74b219a9bcda6b8a5f05bf)
+++ b/central/Dockerfile	(date 1621333942036)
@@ -12,7 +12,8 @@
     && useradd --no-log-init -r -g glowroot glowroot \
     && chown -R glowroot:glowroot /usr/share/glowroot-central \
     && chmod a+x /usr/local/bin/docker-entrypoint.sh \
-    && chmod a+x /usr/local/bin/glowroot-central.sh
+    && chmod a+x /usr/local/bin/glowroot-central.sh \
+    && sed -i 's/^M$//' /usr/local/bin/docker-entrypoint.sh /usr/local/bin/glowroot-central.sh
 
 EXPOSE 4000 8181
 
@@ -24,4 +25,4 @@
 
 ENTRYPOINT ["docker-entrypoint.sh"]
 
-CMD ["glowroot-central.sh"]
+CMD ["glowroot-central.sh"]
\ No newline at end of file
```

**Closed** 2021-11-08 00:02 UTC
