### ISSUE TITLE
Glowroot 0.14.0 IncompatibleClassChangeError: Class jdk.proxy2.$Proxy279

### ISSUE THREAD

**Issue by B-Pete** [glowroot/glowroot#1043] opened 2023-10-10 10:35 UTC
Hi everyone,

To reproduce the issue,  please try this example: https://github.com/B-Pete/spring-jdbc-glowroot

UPDATE:

I do a deeper check, it's not because of running with Docker.

I have different Glowroot config when run with Docker:

```jdbc."captureTransactionLifecycleTraceEntries": true```

Breakpoint is set:
![jdbc_tomcat_datasource](https://github.com/glowroot/glowroot/assets/53456941/209b0c63-b11c-4b53-b16e-5c9b34d635fa)

Next will be result when jump in next step in version 0.13.0 

![jdbc_tomcat_datasource_glowroot13](https://github.com/glowroot/glowroot/assets/53456941/ace31a01-427f-4595-85dd-3c4867b90ed7)

and in 0.14.0, it jumps in a wrong class

![jdbc_tomcat_datasource_glowroot14](https://github.com/glowroot/glowroot/assets/53456941/ba55b50b-d2c1-4f7d-8e74-b212dd6b31a2)

Catch block is never reached since the exception is handled and result an error.

/*******************/

I could run a Spring Boot 3 application in Eclipse (Windows 10) without any issue.
```
2023-10-10 14:59:15.558 INFO  org.glowroot - Glowroot version: 0.14.0, built 2023-05-14 11:36:22 +0000
2023-10-10 14:59:15.564 INFO  org.glowroot - Java version: 17.0.4 (Oracle Corporation / Windows 10)
2023-10-10 14:59:15.565 INFO  org.glowroot - Java args: -XX:+ShowCodeDetailsInExceptionMessages -agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:51717 -javaagent:C:\Users\baoph\working\glowroot\glowroot.jar -javaagent:C:\Users\baoph\working\eclipse\configuration\org.eclipse.osgi\1177\0\.cp\lib\javaagent-shaded.jar
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2023-10-10 14:59:26.117 INFO  org.glowroot - UI listening on 0.0.0.0:4000
```

When I tried to run it in a Docker container and got error:

```
FROM library/alpine:3.16
RUN apk add --no-cache openjdk17-jre
...
ENTRYPOINT ["/home/bin/start.sh"]
```
start.sh: java -jar -javaagent:/home/glowroot/glowroot.jar .../myapp.jar

```
java.lang.IncompatibleClassChangeError: Class jdk.proxy2.$Proxy279 does not implement the requested interface org.glowroot.agent.plugin.jdbc.DataSourceAspect$Connection
at org.glowroot.agent.plugin.jdbc.DataSourceAspect$GetConnectionAdvice.onReturnTraceEntry(DataSourceAspect.java:104)
at org.glowroot.agent.plugin.jdbc.DataSourceAspect$GetConnectionAdvice.onReturn(DataSourceAspect.java:81)
at org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource.getConnection(AbstractRoutingDataSource.java:194)
at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160)
at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118)
at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:721)
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:752)
at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:765)
at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:887)
at c.i.c.client.repository.ClientDatabaseRepository.findOne(ClientDatabaseRepository.java:72)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:568)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
at c.i.c.client.repository.ClientDatabaseRepository$$SpringCGLIB$$0.findOne(<generated>)
at c.i.c.client.service.ClientServiceImpl.findByCode(ClientServiceImpl.java:277)
at c.i.c.client.service.ClientServiceImpl.getClientByCode(ClientServiceImpl.java:665)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:568)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
at c.i.c.client.service.ClientServiceImpl$$SpringCGLIB$$0.getClientByCode(<generated>)
at c.i.c.client.resource.ClientResource.getClientInitData(ClientResource.java:120)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:568)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at c.i.c.http.SimpleCorsFilter.doFilterInternal(SimpleCorsFilter.java:30)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479)
at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapUnsecured$1(ObservationFilterChainDecorator.java:90)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:219)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:738)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:833)

```
I don't know as if the issue in Glowroot, please tell me if you have any idea to fix it.

Thank you.
Pete

**Comment by Nowheresly** [comment] 2023-10-11 06:07
Hi,
do you think it would be possible to provide a minimal application that could reproduce the issue ?

**Comment by B-Pete** [comment] 2023-10-12 10:35
Hi,

I did a double check, I found it maybe a classloader issue. I updated post #1.

**Comment by B-Pete** [comment] 2023-10-12 11:22
I ill create a small application for it.

**Comment by B-Pete** [comment] 2023-12-08 02:44
Hi @Nowheresly 
I made a small application  for the issue https://github.com/B-Pete/spring-jdbc-glowroot
Please have a look at it.
Thank you and best regards,
Pete

**Comment by B-Pete** [comment] 2023-12-08 02:54
To workround, I have to disable this: jdbc."captureTransactionLifecycleTraceEntries": false

**Comment by Nowheresly** [comment] 2024-01-13 17:59
Hi @B-Pete 
I just tested with your demo repo with the latest version of glowroot available [here](https://github.com/glowroot/glowroot/releases/tag/v0.14.1-beta.6).
And the issue is fixed with that version.
I would recommend to switch to the latest version of glowroot.

**Closed** 2024-01-28 11:19 UTC
